### ISSUE TITLE
Add images

### ISSUE THREAD

**Issue by tgum** [dlollia/test#4]
You *should* add pictures to your poem.

**Comment by dlollia** [comment]
Thank you for the **idea**!

**Comment by dlollia** [comment]
Never mind

**Comment by tgum** [comment]
:x:  :confused:

**Comment by dlollia** [comment]
By the way you could look at the changes there:
6eb3412e283957bc263f1708acf9dccf8e6c0eb6

**Comment by tgum** [comment]
:smiley: good #4 is closed
